import React,{useState,useCallback}from'react';
import {GameItem}from'../../types'; import {GameContainer}from'../common/GameContainer'; import {GameOverModal}from'../common/GameOverModal'; import {sound}from'../../utils/audio'; import {Flame,Trophy,Sparkles,Shield,FileText,Scissors,Hand,Orbit,RotateCcw}from'lucide-react';
interface RPSGameProps{game:GameItem;highScore:number;onGameOver:(score:number,isWin:boolean)=>void;onBack:()=>void;soundEnabled:boolean;onToggleSound:()=>void}
type Choice='rock'|'paper'|'scissors'|'lizard'|'spock';
interface Weapon{id:Choice;label:string;beats:Choice[];verb:Record<string,string>;color:string;icon:React.ReactNode}
const icon=(id:Choice,size=42)=> id==='rock'?<Hand size={size} strokeWidth={2.5}/>:id==='paper'?<FileText size={size} strokeWidth={2.4}/>:id==='scissors'?<Scissors size={size} strokeWidth={2.5}/>:id==='lizard'?<span className="rps-emoji">🦎</span>:<span className="rps-emoji">🖖</span>;
const make=(id:Choice,label:string,beats:Choice[],verb:Record<string,string>,color:string):Weapon=>({id,label,beats,verb,color,icon:icon(id)});
const WEAPONS:Record<Choice,Weapon>={rock:make('rock','Rock',['scissors','lizard'],{scissors:'crushes',lizard:'crushes'},'violet'),paper:make('paper','Paper',['rock','spock'],{rock:'covers',spock:'disproves'},'cyan'),scissors:make('scissors','Scissors',['paper','lizard'],{paper:'cuts',lizard:'decapitates'},'rose'),lizard:make('lizard','Lizard',['spock','paper'],{spock:'poisons',paper:'eats'},'lime'),spock:make('spock','Spock',['scissors','rock'],{scissors:'smashes',rock:'vaporizes'},'amber')};
export const RockPaperScissorsGame:React.FC<RPSGameProps>=({game,highScore,onGameOver,onBack,soundEnabled,onToggleSound})=>{
 const [isExtended,setIsExtended]=useState(false),[playerChoice,setPlayerChoice]=useState<Choice|null>(null),[aiChoice,setAiChoice]=useState<Choice|null>(null),[roundResult,setRoundResult]=useState<'win'|'lose'|'tie'|null>(null),[roundDescription,setRoundDescription]=useState('Choose your weapon to start.'),[streak,setStreak]=useState(0),[playerWins,setPlayerWins]=useState(0),[aiWins,setAiWins]=useState(0),[isRevealing,setIsRevealing]=useState(false),[modal,setModal]=useState(false);
 const activeWeapons:Choice[]=isExtended?['rock','paper','scissors','lizard','spock']:['rock','paper','scissors'];
 const resetGame=useCallback(()=>{setPlayerChoice(null);setAiChoice(null);setRoundResult(null);setRoundDescription('Choose your weapon to start.');setStreak(0);setPlayerWins(0);setAiWins(0);setIsRevealing(false);setModal(false)},[]);
 const playRound=(choice:Choice)=>{if(isRevealing)return;sound.playTap();setPlayerChoice(choice);setAiChoice(null);setIsRevealing(true);setRoundResult(null);setRoundDescription('The AI is thinking...');setTimeout(()=>{const cpu=activeWeapons[Math.floor(Math.random()*activeWeapons.length)];setAiChoice(cpu);setIsRevealing(false);if(choice===cpu){sound.playMove();setRoundResult('tie');setRoundDescription(`Both chose ${WEAPONS[choice].label}. It's a draw — play again!`)}else if(WEAPONS[choice].beats.includes(cpu)){sound.playWin();const action=WEAPONS[choice].verb[cpu]||'beats';setRoundResult('win');setRoundDescription(`${WEAPONS[choice].label} ${action} ${WEAPONS[cpu].label}. You take the round!`);setStreak(s=>s+1);setPlayerWins(w=>{const n=w+1;if(n>=5){setModal(true);onGameOver((streak+1)*120,true)}return n})}else{sound.playError();const action=WEAPONS[cpu].verb[choice]||'beats';setRoundResult('lose');setRoundDescription(`${WEAPONS[cpu].label} ${action} ${WEAPONS[choice].label}. The AI takes this one.`);setStreak(0);setAiWins(w=>{const n=w+1;if(n>=5){setModal(true);onGameOver(streak*50,false)}return n})}},650)};
 const weaponCard=(choice:Choice|null,side:'you'|'ai')=>{const weapon=choice?WEAPONS[choice]:null;return <div className={`rps-fighter ${side} ${weapon?weapon.color:''} ${isRevealing&&side==='ai'?'thinking':''}`}><div className="rps-fighter-label">{side==='you'?'YOU':'AI BOT'}</div><div className="rps-fighter-icon">{isRevealing&&side==='ai'?<Orbit className="rps-orbit" size={48}/>:weapon?weapon.icon:side==='ai'?<Shield size={46}/>:<Sparkles size={46}/>}</div><strong>{weapon?weapon.label:isRevealing&&side==='ai'?'Choosing...':side==='you'?'Pick a weapon':'Waiting'}</strong></div>}
 return <GameContainer game={game} score={streak} highScore={highScore} onBack={onBack} onRestart={resetGame} soundEnabled={soundEnabled} onToggleSound={onToggleSound} extraHeaderControls={<button onClick={()=>{setIsExtended(v=>!v);resetGame()}} className="rps-mode-toggle">{isExtended?'5-Way Battle':'Classic 3-Way'}</button>}>
  <div className="rps-stage select-none">
   <section className="rps-scoreboard"><div className="rps-score player"><span>PLAYER</span><b>{playerWins}</b></div><div className="rps-streak"><Flame/><strong>{streak}</strong><span>WIN STREAK</span></div><div className="rps-score ai"><span>AI BOT</span><b>{aiWins}</b></div><div className="rps-race">First to 5 wins <div><i style={{width:`${Math.min(100,playerWins*20)}%`}}/><em style={{width:`${Math.min(100,aiWins*20)}%`}}/></div></div></section>
   <section className={`rps-arena ${roundResult||''}`}><div className="rps-arena-glow"/>{weaponCard(playerChoice,'you')}<div className="rps-vs"><span>ROUND</span><b>VS</b><small>{playerWins+aiWins+1}</small></div>{weaponCard(aiChoice,'ai')}</section>
   <div className={`rps-result ${roundResult||'idle'}`}><div>{roundResult==='win'?<Trophy/>:roundResult==='lose'?<Shield/>:<Sparkles/>}</div><p>{roundDescription}</p></div>
   <section className={`rps-weapons ${isExtended?'five':''}`}>{activeWeapons.map(id=>{const w=WEAPONS[id];return <button key={id} disabled={isRevealing} onClick={()=>playRound(id)} className={`rps-weapon ${w.color} ${playerChoice===id?'selected':''}`}><span>{w.icon}</span><strong>{w.label}</strong><small>{w.beats.map(x=>WEAPONS[x].label).join(' + ')}</small></button>})}</section>
   <div className="rps-footer-tip"><Sparkles size={15}/> <span>Choose a weapon. The AI reveals after you lock yours in.</span><button onClick={resetGame}><RotateCcw size={14}/> Reset match</button></div>
  </div>
  <GameOverModal isOpen={modal} isWin={playerWins>=5} score={streak*100} highScore={highScore} title={playerWins>=5?'Match Champion!':'AI Takes the Match'} message={playerWins>=5?'Five round victories. The championship is yours!':'The AI reached five wins first. Run it back?'} onPlayAgain={resetGame} onHome={onBack}/>
 </GameContainer>
}
